import cron from 'node-cron'
import axios, { AxiosResponse} from "axios"

import { setPropertiesCache } from '../cache/propertyEstateCache'

const SAMPLE_DATA = [
  {
    id: 942,
    propiedad: 'A-1',
    area: 126,
    tipo: 'Lote',
    clase_tipo: 'Esquina',
    modelo: '120.00',
    ubicacion: 'Manzana A',
    estado: 'disponible',
    fin_de_obra: '2025-12-01 00:00:00',
    fase: null,
    bloqueo: null,
    precio: 190000,
    precio_sugerido: 223125,
    proyectos_id: 6,
    habitaciones: null,
    baños: null,
    parqueos: null,
    m2construccion: null,
    largo: 7,
    ancho: 18,
    año: 2025,
    titulo: 'Precioso Lote de 7x18, Legado Cobán',
    descripcion: 'Precioso lote de 126 m² ubicado en Legado Cobán, cerca de la garita principal de acceso, excelente vista a la ciudad de Cobán, rodeado de naturaleza y aire fresco.',
    detalles: 'Topografía plana, Forma regular, Acceso a agua potable',
    descripcion_corta: 'Lote de esquina de 126 m² con vista a Cobán.',
    caracteristicas: 'Calles pavimentadas, Drenajes, Seguridad 24/7',
    latitud: 15.4716,
    longitud: -90.3792,
    comision_referencia: '750.00',
    comision_directa: '1500.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 6,
      nombre_proyecto: 'Club Del Bosque',
      direccion: 'Km 212 Ruta a Cobán, Alta Verapaz',
      tipo: 'Lotes',
      ubicacion: 'Alta Verapaz',
      estado: 'Venta',
        created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop942a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop942b/800/600', formato: 'imagen' },
      { tipo: 'promocional1', url: 'https://picsum.photos/seed/prop942c/800/600', formato: 'imagen' },
    ],
  },
  {
    id: 943,
    propiedad: 'B-3',
    area: 180,
    tipo: 'Lote',
    clase_tipo: 'Interior',
    modelo: '180.00',
    ubicacion: 'Manzana B',
    estado: 'disponible',
    fin_de_obra: '2025-12-01 00:00:00',
    fase: null,
    bloqueo: null,
    precio: 145000,
    precio_sugerido: 168000,
    proyectos_id: 6,
    habitaciones: null,
    baños: null,
    parqueos: null,
    m2construccion: null,
    largo: 10,
    ancho: 18,
    año: 2025,
    titulo: 'Lote Interior 10x18 en Club Del Bosque',
    descripcion: 'Amplio lote de 180 m² en zona residencial privada rodeada de bosque, con acceso controlado y todas las urbanizaciones completas.',
    detalles: 'Topografía plana, Fácil acceso, Servicios completos',
    descripcion_corta: 'Lote plano de 180 m² en zona residencial exclusiva.',
    caracteristicas: 'Calles pavimentadas, Alumbrado público, Agua potable, Drenajes',
    latitud: 15.4720,
    longitud: -90.3800,
    comision_referencia: '580.00',
    comision_directa: '1160.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 6,
      nombre_proyecto: 'Club Del Bosque',
      direccion: 'Km 212 Ruta a Cobán, Alta Verapaz',
      tipo: 'Lotes',
      ubicacion: 'Alta Verapaz',
      estado: 'Venta',created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop943a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop943b/800/600', formato: 'imagen' },
    ],
  },
  {
    id: 944,
    propiedad: 'Casa-12',
    area: 220,
    tipo: 'Casa',
    clase_tipo: 'Residencial',
    modelo: 'Modelo Jade',
    ubicacion: 'Sector Norte',
    estado: 'disponible',
    fin_de_obra: '2025-08-01 00:00:00',
    fase: '1',
    bloqueo: 'A',
    precio: 420000,
    precio_sugerido: 465000,
    proyectos_id: 7,
    habitaciones: 4,
    baños: 3,
    parqueos: 2,
    m2construccion: 185,
    largo: null,
    ancho: null,
    año: 2025,
    titulo: 'Casa Modelo Jade — 4 habitaciones en Santa Catarina Pinula',
    descripcion: 'Hermosa casa de dos niveles con acabados de primera. Sala, comedor, cocina abierta, área de servicio, jardín y terraza. Ubicada en condominio cerrado con seguridad 24/7.',
    detalles: 'Pisos de porcelanato, Ventanas de aluminio, Cocina con isla, Techo de losa tradicional',
    descripcion_corta: 'Casa de 4 hab. con acabados premium en condominio cerrado.',
    caracteristicas: 'Piscina comunitaria, Gimnasio, Parque infantil, Seguridad 24/7, Salón de eventos',
    latitud: 14.5636,
    longitud: -90.4873,
    comision_referencia: '1680.00',
    comision_directa: '3360.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 7,
      nombre_proyecto: 'Residencial Los Pinos',
      direccion: 'Km 18.5 Carretera a Santa Catarina Pinula',
      tipo: 'Casas',
      ubicacion: 'Santa Catarina Pinula',
      estado: 'Venta',created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop944a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop944b/800/600', formato: 'imagen' },
      { tipo: 'promocional1', url: 'https://picsum.photos/seed/prop944c/800/600', formato: 'imagen' },
      { tipo: 'promocional2', url: 'https://picsum.photos/seed/prop944d/800/600', formato: 'imagen' },
    ],
  },
  {
    id: 945,
    propiedad: 'Apto-5B',
    area: 95,
    tipo: 'Apartamento',
    clase_tipo: 'Estándar',
    modelo: 'Modelo B',
    ubicacion: 'Torre 1, Nivel 5',
    estado: 'disponible',
    fin_de_obra: '2026-03-01 00:00:00',
    fase: '2',
    bloqueo: 'Torre 1',
    precio: 210000,
    precio_sugerido: 235000,
    proyectos_id: 8,
    habitaciones: 2,
    baños: 2,
    parqueos: 1,
    m2construccion: 95,
    largo: null,
    ancho: null,
    año: 2026,
    titulo: 'Apartamento 2 Habitaciones — Torre 1, Zona 15',
    descripcion: 'Moderno apartamento en zona 15 con vista panorámica a la ciudad. Diseño abierto, cocina equipada, balcón privado y acabados contemporáneos de alta calidad.',
    detalles: 'Pisos de madera laminada, Ventanas termopanel, Cocina con granito, Balcón de 8 m²',
    descripcion_corta: 'Apto. moderno con vista panorámica en Zona 15.',
    caracteristicas: 'Rooftop, Piscina, Gimnasio, Lobby con recepción, Seguridad 24/7, Estacionamiento de visitas',
    latitud: 14.6036,
    longitud: -90.5073,
    comision_referencia: '840.00',
    comision_directa: '1680.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 8,
      nombre_proyecto: 'Vivalta Zona 15',
      direccion: '15 Av. 18-20, Zona 15, Vista Hermosa',
      tipo: 'Apartamentos',
      ubicacion: 'Zona 15, Guatemala',
      estado: 'Preventas',created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop945a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop945b/800/600', formato: 'imagen' },
      { tipo: 'promocional1', url: 'https://picsum.photos/seed/prop945c/800/600', formato: 'imagen' },
    ],
  },
  {
    id: 946,
    propiedad: 'Casa-07',
    area: 310,
    tipo: 'Casa',
    clase_tipo: 'Premium',
    modelo: 'Modelo Esmeralda',
    ubicacion: 'Sector Sur',
    estado: 'reservado',
    fin_de_obra: '2025-06-01 00:00:00',
    fase: '1',
    bloqueo: 'B',
    precio: 620000,
    precio_sugerido: 690000,
    proyectos_id: 7,
    habitaciones: 5,
    baños: 4,
    parqueos: 3,
    m2construccion: 260,
    largo: null,
    ancho: null,
    año: 2025,
    titulo: 'Casa Premium Esmeralda — 5 hab. con piscina privada',
    descripcion: 'Exclusiva casa de 310 m² con piscina privada, jardín amplio y acabados de lujo. Cocina gourmet, sala de estar doble altura y cuarto de servicio independiente.',
    detalles: 'Piscina privada de 30 m², Jardín de 80 m², Doble altura en sala, Cuarto de servicio con baño',
    descripcion_corta: 'Casa premium 5 hab. con piscina privada en condominio exclusivo.',
    caracteristicas: 'Piscina privada, Jardín, Club house, Cancha de tenis, Seguridad 24/7',
    latitud: 14.5640,
    longitud: -90.4880,
    comision_referencia: '2480.00',
    comision_directa: '4960.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 7,
      nombre_proyecto: 'Residencial Los Pinos',
      direccion: 'Km 18.5 Carretera a Santa Catarina Pinula',
      tipo: 'Casas',
      ubicacion: 'Santa Catarina Pinula',
      estado: 'Venta',created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop946a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop946b/800/600', formato: 'imagen' },
      { tipo: 'promocional1', url: 'https://picsum.photos/seed/prop946c/800/600', formato: 'imagen' },
    ],
  },
  {
    id: 947,
    propiedad: 'Apto-3A',
    area: 130,
    tipo: 'Apartamento',
    clase_tipo: 'Premium',
    modelo: 'Modelo A+',
    ubicacion: 'Torre 2, Nivel 8',
    estado: 'disponible',
    fin_de_obra: '2026-03-01 00:00:00',
    fase: '2',
    bloqueo: 'Torre 2',
    precio: 320000,
    precio_sugerido: 358000,
    proyectos_id: 8,
    habitaciones: 3,
    baños: 2,
    parqueos: 2,
    m2construccion: 130,
    largo: null,
    ancho: null,
    año: 2026,
    titulo: 'Penthouse 3 Habitaciones — Nivel 8, Zona 15',
    descripcion: 'Lujoso penthouse con terraza privada de 45 m² y vista de 180° a la ciudad de Guatemala. Acabados de primer nivel y tecnología domótica integrada.',
    detalles: 'Terraza privada 45 m², Vista 180° ciudad, Domótica, Jacuzzi en terraza',
    descripcion_corta: 'Penthouse 3 hab. con terraza y vista panorámica en Zona 15.',
    caracteristicas: 'Terraza privada, Jacuzzi, Domótica, Rooftop comunitario, Lobby VIP',
    latitud: 14.6040,
    longitud: -90.5080,
    comision_referencia: '1280.00',
    comision_directa: '2560.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 8,
      nombre_proyecto: 'Vivalta Zona 15',
      direccion: '15 Av. 18-20, Zona 15, Vista Hermosa',
      tipo: 'Apartamentos',
      ubicacion: 'Zona 15, Guatemala',
      estado: 'Preventas',created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop947a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop947b/800/600', formato: 'imagen' },
      { tipo: 'promocional1', url: 'https://picsum.photos/seed/prop947c/800/600', formato: 'imagen' },
      { tipo: 'promocional2', url: 'https://picsum.photos/seed/prop947d/800/600', formato: 'imagen' },
    ],
  },
  {
    id: 948,
    propiedad: 'C-8',
    area: 200,
    tipo: 'Lote',
    clase_tipo: 'Esquina',
    modelo: '200.00',
    ubicacion: 'Manzana C',
    estado: 'disponible',
    fin_de_obra: '2025-12-01 00:00:00',
    fase: null,
    bloqueo: null,
    precio: 260000,
    precio_sugerido: 295000,
    proyectos_id: 6,
    habitaciones: null,
    baños: null,
    parqueos: null,
    m2construccion: null,
    largo: 10,
    ancho: 20,
    año: 2025,
    titulo: 'Lote Esquina 10x20 — Vista al bosque, Club Del Bosque',
    descripcion: 'Espectacular lote de esquina de 200 m² con frente doble y vista privilegiada al área boscosa del proyecto. Ideal para construcción de casa con jardín amplio.',
    detalles: 'Frente doble, Vista al bosque, Topografía plana, Todos los servicios',
    descripcion_corta: 'Lote esquina 200 m² con vista al bosque y frente doble.',
    caracteristicas: 'Calles pavimentadas, Alumbrado, Agua potable, Drenajes, Seguridad 24/7',
    latitud: 15.4725,
    longitud: -90.3810,
    comision_referencia: '1040.00',
    comision_directa: '2080.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 6,
      nombre_proyecto: 'Club Del Bosque',
      direccion: 'Km 212 Ruta a Cobán, Alta Verapaz',
      tipo: 'Lotes',
      ubicacion: 'Alta Verapaz',
      estado: 'Venta',created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop948a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop948b/800/600', formato: 'imagen' },
    ],
  },
  {
    id: 949,
    propiedad: 'Casa-03',
    area: 165,
    tipo: 'Casa',
    clase_tipo: 'Residencial',
    modelo: 'Modelo Roble',
    ubicacion: 'Sector Oriente',
    estado: 'vendido',
    fin_de_obra: '2024-10-01 00:00:00',
    fase: '1',
    bloqueo: 'C',
    precio: 285000,
    precio_sugerido: 310000,
    proyectos_id: 9,
    habitaciones: 3,
    baños: 2,
    parqueos: 1,
    m2construccion: 140,
    largo: null,
    ancho: null,
    año: 2024,
    titulo: 'Casa Modelo Roble — 3 hab. en Mixco',
    descripcion: 'Cómoda casa familiar en condominio cerrado en Mixco. Sala-comedor integrados, cocina amplia, patio trasero y cuarto de lavandería.',
    detalles: 'Patio trasero de 25 m², Cuarto de lavandería, Cocina con desayunador',
    descripcion_corta: 'Casa familiar 3 hab. en condominio cerrado en Mixco.',
    caracteristicas: 'Parque, Juegos infantiles, Seguridad 24/7, Estacionamiento de visitas',
    latitud: 14.6308,
    longitud: -90.6068,
    comision_referencia: '1140.00',
    comision_directa: '2280.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 9,
      nombre_proyecto: 'Villas del Valle',
      direccion: 'Km 14.5 Calzada Roosevelt, Mixco',
      tipo: 'Casas',
      ubicacion: 'Mixco',
      estado: 'Venta',created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop949a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop949b/800/600', formato: 'imagen' },
    ],
  },
  {
    id: 950,
    propiedad: 'Apto-2C',
    area: 72,
    tipo: 'Apartamento',
    clase_tipo: 'Estándar',
    modelo: 'Modelo C',
    ubicacion: 'Torre 1, Nivel 2',
    estado: 'disponible',
    fin_de_obra: '2026-03-01 00:00:00',
    fase: '2',
    bloqueo: 'Torre 1',
    precio: 155000,
    precio_sugerido: 172000,
    proyectos_id: 8,
    habitaciones: 1,
    baños: 1,
    parqueos: 1,
    m2construccion: 72,
    largo: null,
    ancho: null,
    año: 2026,
    titulo: 'Apartamento 1 Habitación — Zona 15, Entrega 2026',
    descripcion: 'Apartamento compacto y funcional ideal para jóvenes profesionales o inversión. Diseño eficiente con acabados modernos y área de trabajo integrada.',
    detalles: 'Diseño eficiente, Área de trabajo, Cocina abierta, Balcón de 5 m²',
    descripcion_corta: 'Apto. 1 hab. moderno ideal para inversión en Zona 15.',
    caracteristicas: 'Rooftop, Gimnasio, Coworking, Lobby con recepción, Seguridad 24/7',
    latitud: 14.6038,
    longitud: -90.5075,
    comision_referencia: '620.00',
    comision_directa: '1240.00',
    created_at: null,
    updated_at: null,
    proyecto: {
      id: 8,
      nombre_proyecto: 'Vivalta Zona 15',
      direccion: '15 Av. 18-20, Zona 15, Vista Hermosa',
      tipo: 'Apartamentos',
      ubicacion: 'Zona 15, Guatemala',
      estado: 'Preventas',created_at: "",
        updated_at: "",
        aprobacion12cuotas: null,
    },
    imagenes: [
      { tipo: 'ingreso', url: 'https://picsum.photos/seed/prop950a/800/600', formato: 'imagen' },
      { tipo: 'panoramica', url: 'https://picsum.photos/seed/prop950b/800/600', formato: 'imagen' },
      { tipo: 'promocional1', url: 'https://picsum.photos/seed/prop950c/800/600', formato: 'imagen' },
    ],
  },
];

const fetchCatalog = async () => {

    try {

        const url = process.env['URL_CATALOG'] || ""
        const apiKey = process.env['APIKEY_CATALOG']

        const response = await axios.get(url, {
            headers: {
                'x-api-key': apiKey,
                "Content-Type": "application/json"
            }
        }).then((response: AxiosResponse) => response.data)

        if (response.success) {
            setPropertiesCache(response.data)
            console.log(`[syncCatalog] Cache updated — ${response.data.length} catalog at ${new Date().toISOString()}`)
        } else {
            setPropertiesCache(SAMPLE_DATA)
            console.log("[syncCatalog] Error obtaining catalog");
        }

    } catch (error: unknown) {

        if (error instanceof Error) {
            console.log("Error updating catalog:", error.message);
            return
        }

        console.log("Unknown error updating catalog:", error);

    }

}

export const syncCatalog = async () => {

    await fetchCatalog()

    cron.schedule('*/15 * * * *', async () => {
        await fetchCatalog()
    })

}
